// Generated by Claude from Figma variables via DesignBridge.
// To update: export from Figma using the DesignBridge plugin and ask Claude to sync.

import 'package:flutter/material.dart';

class AppBorders {
  AppBorders._();
}
