// Generated by Claude from Figma variables via DesignBridge.
// To update: export from Figma using the DesignBridge plugin and ask Claude to sync.
//
// Naming convention (v2.0.0):
//   PepperCore* = primitives (raw values). Don't use directly.
//   Pepper*     = semantic tokens. Use these.

/// Semantic border-width tokens.
class PepperBorderWidth {
  static const strokeLg = 8;

  static const strokeMd = 4;

  static const strokeNone = 0;

  static const strokeSm = 2;

  static const strokeXs = 1;

  static const iconIcon12 = 0.75;

  static const iconIcon16 = 1;

  static const iconIcon20 = 1.25;

  static const iconIcon24 = 1.5;

  static const iconIcon28 = 1.75;

  static const iconIcon32 = 2;

  static const iconIcon36 = 2.25;

  static const iconIcon40 = 2.5;

  static const iconIcon48 = 3;

  static const iconIcon56 = 3.5;

  static const iconIcon64 = 4;

  PepperBorderWidth._();
}
