// Generated by Claude from Figma variables via DesignBridge.
// To update: export from Figma using the DesignBridge plugin and ask Claude to sync.
//
// Naming convention (v2.0.0):
//   PepperCore* = primitives (raw values). Don't use directly.
//   Pepper*     = semantic tokens. Use these.

import 'package:flutter/material.dart';

/// Reserved for composite BorderSide presets. Currently empty — see
/// `PepperBorderWidth` (borders.dart) and `PepperColors` for building your own.
class PepperBorderSides {
  PepperBorderSides._();
}
