// Generated by Claude from Figma variables via DesignBridge.
// To update: export from Figma using the DesignBridge plugin and ask Claude to sync.
//
// Naming convention (v2.0.0):
//   PepperCore* = primitives (raw values). Don't use directly in product code.
//   Pepper*     = semantic / component / state / static / overlay. Use these.

import 'package:flutter/material.dart';

/// Primitive colour scales. Not intended for direct use in product code.
class PepperCoreColors {
  static const colorBrandCryptoOrange100 = Color(0xffffecd3);

  static const colorBrandCryptoOrange200 = Color(0xffffd4a5);

  static const colorBrandCryptoOrange300 = Color(0xffffb66d);

  static const colorBrandCryptoOrange400 = Color(0xffff8b32);

  static const colorBrandCryptoOrange50 = Color(0xfffff6ec);

  static const colorBrandCryptoOrange500 = Color(0xffff6a0a);

  static const colorBrandCryptoOrange600 = Color(0xffff5000);

  static const colorBrandCryptoOrange700 = Color(0xffcc3702);

  static const colorBrandCryptoOrange800 = Color(0xffa12c0b);

  static const colorBrandCryptoOrange900 = Color(0xff82270c);

  static const colorBrandCryptoOrange950 = Color(0xff461004);

  static const colorBrandPrimaryBlue100 = Color(0xff99c1fd);

  static const colorBrandPrimaryBlue200 = Color(0xff67a3fc);

  static const colorBrandPrimaryBlue300 = Color(0xff3484fb);

  static const colorBrandPrimaryBlue400 = Color(0xff0165fa);

  static const colorBrandPrimaryBlue50 = Color(0xffe6f0ff);

  static const colorBrandPrimaryBlue500 = Color(0xff0032c7);

  static const colorBrandPrimaryBlue600 = Color(0xff000094);

  static const colorBrandPrimaryBlue700 = Color(0xff000061);

  static const colorBrandSecondaryCyan100 = Color(0xffcefafe);

  static const colorBrandSecondaryCyan200 = Color(0xffa2f4fd);

  static const colorBrandSecondaryCyan300 = Color(0xff53eafd);

  static const colorBrandSecondaryCyan400 = Color(0xff00d3f3);

  static const colorBrandSecondaryCyan50 = Color(0xffecfeff);

  static const colorBrandSecondaryCyan500 = Color(0xff00b8db);

  static const colorBrandSecondaryCyan600 = Color(0xff0092b8);

  static const colorBrandSecondaryCyan700 = Color(0xff007595);

  static const colorBrandSecondaryCyan800 = Color(0xff005f78);

  static const colorBrandSecondaryCyan900 = Color(0xff104e64);

  static const colorBrandSecondaryCyan950 = Color(0xff053345);

  static const colorDecorativeLime100 = Color(0xffd3f1a7);

  static const colorDecorativeLime200 = Color(0xffbde97c);

  static const colorDecorativeLime300 = Color(0xffb3df72);

  static const colorDecorativeLime400 = Color(0xff94c748);

  static const colorDecorativeLime50 = Color(0xffefffd6);

  static const colorDecorativeLime500 = Color(0xff82b536);

  static const colorDecorativeLime600 = Color(0xff4d7c0f);

  static const colorDecorativeLime700 = Color(0xff1a2e05);

  static const colorDecorativeMagenta100 = Color(0xfffdd0ec);

  static const colorDecorativeMagenta200 = Color(0xfffcb6e1);

  static const colorDecorativeMagenta300 = Color(0xfff797d2);

  static const colorDecorativeMagenta400 = Color(0xffe774bb);

  static const colorDecorativeMagenta50 = Color(0xffffecf8);

  static const colorDecorativeMagenta500 = Color(0xffda62ac);

  static const colorDecorativeMagenta600 = Color(0xff9d174d);

  static const colorDecorativeMagenta700 = Color(0xff500724);

  static const colorDecorativeTurquoise100 = Color(0xffd7f9ed);

  static const colorDecorativeTurquoise200 = Color(0xffaef3d9);

  static const colorDecorativeTurquoise300 = Color(0xff99efcf);

  static const colorDecorativeTurquoise400 = Color(0xff47e0a8);

  static const colorDecorativeTurquoise50 = Color(0xffecfcf6);

  static const colorDecorativeTurquoise500 = Color(0xff3ac190);

  static const colorDecorativeTurquoise600 = Color(0xff0d9488);

  static const colorDecorativeTurquoise700 = Color(0xff134e4a);

  static const colorDecorativeViolet100 = Color(0xffe3c0f0);

  static const colorDecorativeViolet200 = Color(0xffe6a5fe);

  static const colorDecorativeViolet300 = Color(0xffd460ff);

  static const colorDecorativeViolet400 = Color(0xffaa30d8);

  static const colorDecorativeViolet50 = Color(0xfffcf4ff);

  static const colorDecorativeViolet500 = Color(0xff7f00ad);

  static const colorDecorativeViolet600 = Color(0xff3f144f);

  static const colorDecorativeViolet700 = Color(0xff260333);

  static const colorDecorativeYellow100 = Color(0xfff5e989);

  static const colorDecorativeYellow200 = Color(0xffefdd4e);

  static const colorDecorativeYellow300 = Color(0xffeed12b);

  static const colorDecorativeYellow400 = Color(0xffddb30e);

  static const colorDecorativeYellow50 = Color(0xfffef7c8);

  static const colorDecorativeYellow500 = Color(0xffcf9f02);

  static const colorDecorativeYellow600 = Color(0xff916a00);

  static const colorDecorativeYellow700 = Color(0xff451a03);

  static const colorNeutral100 = Color(0xfff5f5f5);

  static const colorNeutral200 = Color(0xffe5e5e5);

  static const colorNeutral300 = Color(0xffd4d4d4);

  static const colorNeutral400 = Color(0xffa1a1a1);

  static const colorNeutral50 = Color(0xfffafafa);

  static const colorNeutral500 = Color(0xff737373);

  static const colorNeutral600 = Color(0xff525252);

  static const colorNeutral700 = Color(0xff404040);

  static const colorNeutral800 = Color(0xff262626);

  static const colorNeutral900 = Color(0xff171717);

  static const colorNeutral950 = Color(0xff0a0a0a);

  static const colorNeutralBlack = Color(0xff000000);

  static const colorNeutralWhite = Color(0xffffffff);

  static const colorSystemGreen100 = Color(0xffdcfce7);

  static const colorSystemGreen200 = Color(0xffb9f8cf);

  static const colorSystemGreen300 = Color(0xff7bf1a8);

  static const colorSystemGreen400 = Color(0xff05df72);

  static const colorSystemGreen50 = Color(0xfff0fdf4);

  static const colorSystemGreen500 = Color(0xff00c950);

  static const colorSystemGreen600 = Color(0xff00a63e);

  static const colorSystemGreen700 = Color(0xff008236);

  static const colorSystemGreen800 = Color(0xff016630);

  static const colorSystemGreen900 = Color(0xff0d542b);

  static const colorSystemGreen950 = Color(0xff032e15);

  static const colorSystemOrange100 = Color(0xffffedd4);

  static const colorSystemOrange200 = Color(0xffffd6a8);

  static const colorSystemOrange300 = Color(0xffffb86a);

  static const colorSystemOrange400 = Color(0xffff8904);

  static const colorSystemOrange50 = Color(0xfffff7ed);

  static const colorSystemOrange500 = Color(0xffff6900);

  static const colorSystemOrange600 = Color(0xfff54900);

  static const colorSystemOrange700 = Color(0xffca3500);

  static const colorSystemOrange800 = Color(0xff9f2d00);

  static const colorSystemOrange900 = Color(0xff7e2a0c);

  static const colorSystemOrange950 = Color(0xff441306);

  static const colorSystemRed100 = Color(0xffffe2e2);

  static const colorSystemRed200 = Color(0xffffc9c9);

  static const colorSystemRed300 = Color(0xffffa2a2);

  static const colorSystemRed400 = Color(0xffff6467);

  static const colorSystemRed50 = Color(0xfffef2f2);

  static const colorSystemRed500 = Color(0xfffb2c36);

  static const colorSystemRed600 = Color(0xffe7000b);

  static const colorSystemRed700 = Color(0xffc10007);

  static const colorSystemRed800 = Color(0xff9f0712);

  static const colorSystemRed900 = Color(0xff82181a);

  static const colorSystemRed950 = Color(0xff460809);

  static const opacityColorBrandCryptoOrange600Opacity0 = Color(0x00ff5000);

  static const opacityColorBrandCryptoOrange600Opacity10 = Color(0x1aff5000);

  static const opacityColorBrandCryptoOrange600Opacity100 = Color(0xffff5000);

  static const opacityColorBrandCryptoOrange600Opacity15 = Color(0x26ff5000);

  static const opacityColorBrandCryptoOrange600Opacity20 = Color(0x33ff5000);

  static const opacityColorBrandCryptoOrange600Opacity25 = Color(0x40ff5000);

  static const opacityColorBrandCryptoOrange600Opacity30 = Color(0x4dff5000);

  static const opacityColorBrandCryptoOrange600Opacity35 = Color(0x59ff5000);

  static const opacityColorBrandCryptoOrange600Opacity40 = Color(0x66ff5000);

  static const opacityColorBrandCryptoOrange600Opacity45 = Color(0x73ff5000);

  static const opacityColorBrandCryptoOrange600Opacity5 = Color(0x0dff5000);

  static const opacityColorBrandCryptoOrange600Opacity50 = Color(0x80ff5000);

  static const opacityColorBrandCryptoOrange600Opacity55 = Color(0x8cff5000);

  static const opacityColorBrandCryptoOrange600Opacity60 = Color(0x99ff5000);

  static const opacityColorBrandCryptoOrange600Opacity65 = Color(0xa6ff5000);

  static const opacityColorBrandCryptoOrange600Opacity70 = Color(0xb2ff5000);

  static const opacityColorBrandCryptoOrange600Opacity75 = Color(0xbfff5000);

  static const opacityColorBrandCryptoOrange600Opacity80 = Color(0xccff5000);

  static const opacityColorBrandCryptoOrange600Opacity85 = Color(0xd9ff5000);

  static const opacityColorBrandCryptoOrange600Opacity90 = Color(0xe5ff5000);

  static const opacityColorBrandCryptoOrange600Opacity95 = Color(0xf2ff5000);

  static const opacityColorBrandPrimaryBlue100Opacity0 = Color(0x0099c1fd);

  static const opacityColorBrandPrimaryBlue100Opacity10 = Color(0x1a99c1fd);

  static const opacityColorBrandPrimaryBlue100Opacity100 = Color(0xff99c1fd);

  static const opacityColorBrandPrimaryBlue100Opacity15 = Color(0x2699c1fd);

  static const opacityColorBrandPrimaryBlue100Opacity20 = Color(0x3399c1fd);

  static const opacityColorBrandPrimaryBlue100Opacity25 = Color(0x4099c1fd);

  static const opacityColorBrandPrimaryBlue100Opacity30 = Color(0x4d99c1fd);

  static const opacityColorBrandPrimaryBlue100Opacity35 = Color(0x5999c1fd);

  static const opacityColorBrandPrimaryBlue100Opacity40 = Color(0x6699c1fd);

  static const opacityColorBrandPrimaryBlue100Opacity45 = Color(0x7399c1fd);

  static const opacityColorBrandPrimaryBlue100Opacity5 = Color(0x0d99c1fd);

  static const opacityColorBrandPrimaryBlue100Opacity50 = Color(0x8099c1fd);

  static const opacityColorBrandPrimaryBlue100Opacity55 = Color(0x8c99c1fd);

  static const opacityColorBrandPrimaryBlue100Opacity60 = Color(0x9999c1fd);

  static const opacityColorBrandPrimaryBlue100Opacity65 = Color(0xa699c1fd);

  static const opacityColorBrandPrimaryBlue100Opacity70 = Color(0xb299c1fd);

  static const opacityColorBrandPrimaryBlue100Opacity75 = Color(0xbf99c1fd);

  static const opacityColorBrandPrimaryBlue100Opacity80 = Color(0xcc99c1fd);

  static const opacityColorBrandPrimaryBlue100Opacity85 = Color(0xd999c1fd);

  static const opacityColorBrandPrimaryBlue100Opacity90 = Color(0xe599c1fd);

  static const opacityColorBrandPrimaryBlue100Opacity95 = Color(0xf299c1fd);

  static const opacityColorBrandPrimaryBlue300Opacity0 = Color(0x003484fb);

  static const opacityColorBrandPrimaryBlue300Opacity10 = Color(0x1a3484fb);

  static const opacityColorBrandPrimaryBlue300Opacity100 = Color(0xff3484fb);

  static const opacityColorBrandPrimaryBlue300Opacity15 = Color(0x263484fb);

  static const opacityColorBrandPrimaryBlue300Opacity20 = Color(0x333484fb);

  static const opacityColorBrandPrimaryBlue300Opacity25 = Color(0x403484fb);

  static const opacityColorBrandPrimaryBlue300Opacity30 = Color(0x4d3484fb);

  static const opacityColorBrandPrimaryBlue300Opacity35 = Color(0x593484fb);

  static const opacityColorBrandPrimaryBlue300Opacity40 = Color(0x663484fb);

  static const opacityColorBrandPrimaryBlue300Opacity45 = Color(0x733484fb);

  static const opacityColorBrandPrimaryBlue300Opacity5 = Color(0x0d3484fb);

  static const opacityColorBrandPrimaryBlue300Opacity50 = Color(0x803484fb);

  static const opacityColorBrandPrimaryBlue300Opacity55 = Color(0x8c3484fb);

  static const opacityColorBrandPrimaryBlue300Opacity60 = Color(0x993484fb);

  static const opacityColorBrandPrimaryBlue300Opacity65 = Color(0xa63484fb);

  static const opacityColorBrandPrimaryBlue300Opacity70 = Color(0xb23484fb);

  static const opacityColorBrandPrimaryBlue300Opacity75 = Color(0xbf3484fb);

  static const opacityColorBrandPrimaryBlue300Opacity80 = Color(0xcc3484fb);

  static const opacityColorBrandPrimaryBlue300Opacity85 = Color(0xd93484fb);

  static const opacityColorBrandPrimaryBlue300Opacity90 = Color(0xe53484fb);

  static const opacityColorBrandPrimaryBlue300Opacity95 = Color(0xf23484fb);

  static const opacityColorBrandPrimaryBlue400Opacity0 = Color(0x000165fa);

  static const opacityColorBrandPrimaryBlue400Opacity10 = Color(0x1a0165fa);

  static const opacityColorBrandPrimaryBlue400Opacity100 = Color(0xff0165fa);

  static const opacityColorBrandPrimaryBlue400Opacity15 = Color(0x260165fa);

  static const opacityColorBrandPrimaryBlue400Opacity20 = Color(0x330165fa);

  static const opacityColorBrandPrimaryBlue400Opacity25 = Color(0x400165fa);

  static const opacityColorBrandPrimaryBlue400Opacity30 = Color(0x4d0165fa);

  static const opacityColorBrandPrimaryBlue400Opacity35 = Color(0x590165fa);

  static const opacityColorBrandPrimaryBlue400Opacity40 = Color(0x660165fa);

  static const opacityColorBrandPrimaryBlue400Opacity45 = Color(0x730165fa);

  static const opacityColorBrandPrimaryBlue400Opacity5 = Color(0x0d0165fa);

  static const opacityColorBrandPrimaryBlue400Opacity50 = Color(0x800165fa);

  static const opacityColorBrandPrimaryBlue400Opacity55 = Color(0x8c0165fa);

  static const opacityColorBrandPrimaryBlue400Opacity60 = Color(0x990165fa);

  static const opacityColorBrandPrimaryBlue400Opacity65 = Color(0xa60165fa);

  static const opacityColorBrandPrimaryBlue400Opacity70 = Color(0xb20165fa);

  static const opacityColorBrandPrimaryBlue400Opacity75 = Color(0xbf0165fa);

  static const opacityColorBrandPrimaryBlue400Opacity80 = Color(0xcc0165fa);

  static const opacityColorBrandPrimaryBlue400Opacity85 = Color(0xd90165fa);

  static const opacityColorBrandPrimaryBlue400Opacity90 = Color(0xe50165fa);

  static const opacityColorBrandPrimaryBlue400Opacity95 = Color(0xf20165fa);

  static const opacityColorBrandSecondaryCyan400Opacity0 = Color(0x0000d3f3);

  static const opacityColorBrandSecondaryCyan400Opacity10 = Color(0x1a00d3f3);

  static const opacityColorBrandSecondaryCyan400Opacity100 = Color(0xff00d3f3);

  static const opacityColorBrandSecondaryCyan400Opacity15 = Color(0x2600d3f3);

  static const opacityColorBrandSecondaryCyan400Opacity20 = Color(0x3300d3f3);

  static const opacityColorBrandSecondaryCyan400Opacity25 = Color(0x4000d3f3);

  static const opacityColorBrandSecondaryCyan400Opacity30 = Color(0x4d00d3f3);

  static const opacityColorBrandSecondaryCyan400Opacity35 = Color(0x5900d3f3);

  static const opacityColorBrandSecondaryCyan400Opacity40 = Color(0x6600d3f3);

  static const opacityColorBrandSecondaryCyan400Opacity45 = Color(0x7300d3f3);

  static const opacityColorBrandSecondaryCyan400Opacity5 = Color(0x0d00d3f3);

  static const opacityColorBrandSecondaryCyan400Opacity50 = Color(0x8000d3f3);

  static const opacityColorBrandSecondaryCyan400Opacity55 = Color(0x8c00d3f3);

  static const opacityColorBrandSecondaryCyan400Opacity60 = Color(0x9900d3f3);

  static const opacityColorBrandSecondaryCyan400Opacity65 = Color(0xa600d3f3);

  static const opacityColorBrandSecondaryCyan400Opacity70 = Color(0xb200d3f3);

  static const opacityColorBrandSecondaryCyan400Opacity75 = Color(0xbf00d3f3);

  static const opacityColorBrandSecondaryCyan400Opacity80 = Color(0xcc00d3f3);

  static const opacityColorBrandSecondaryCyan400Opacity85 = Color(0xd900d3f3);

  static const opacityColorBrandSecondaryCyan400Opacity90 = Color(0xe500d3f3);

  static const opacityColorBrandSecondaryCyan400Opacity95 = Color(0xf200d3f3);

  static const opacityColorNeutralBlackOpacity0 = Color(0x00000000);

  static const opacityColorNeutralBlackOpacity10 = Color(0x1a000000);

  static const opacityColorNeutralBlackOpacity100 = Color(0xff000000);

  static const opacityColorNeutralBlackOpacity15 = Color(0x26000000);

  static const opacityColorNeutralBlackOpacity20 = Color(0x33000000);

  static const opacityColorNeutralBlackOpacity25 = Color(0x40000000);

  static const opacityColorNeutralBlackOpacity30 = Color(0x4d000000);

  static const opacityColorNeutralBlackOpacity35 = Color(0x59000000);

  static const opacityColorNeutralBlackOpacity40 = Color(0x66000000);

  static const opacityColorNeutralBlackOpacity45 = Color(0x73000000);

  static const opacityColorNeutralBlackOpacity5 = Color(0x0d000000);

  static const opacityColorNeutralBlackOpacity50 = Color(0x80000000);

  static const opacityColorNeutralBlackOpacity55 = Color(0x8c000000);

  static const opacityColorNeutralBlackOpacity60 = Color(0x99000000);

  static const opacityColorNeutralBlackOpacity65 = Color(0xa6000000);

  static const opacityColorNeutralBlackOpacity70 = Color(0xb2000000);

  static const opacityColorNeutralBlackOpacity75 = Color(0xbf000000);

  static const opacityColorNeutralBlackOpacity80 = Color(0xcc000000);

  static const opacityColorNeutralBlackOpacity85 = Color(0xd9000000);

  static const opacityColorNeutralBlackOpacity90 = Color(0xe5000000);

  static const opacityColorNeutralBlackOpacity95 = Color(0xf2000000);

  static const opacityColorNeutralNeutral100Opacity0 = Color(0x00f5f5f5);

  static const opacityColorNeutralNeutral100Opacity10 = Color(0x1af5f5f5);

  static const opacityColorNeutralNeutral100Opacity100 = Color(0xfff5f5f5);

  static const opacityColorNeutralNeutral100Opacity15 = Color(0x26f5f5f5);

  static const opacityColorNeutralNeutral100Opacity20 = Color(0x33f5f5f5);

  static const opacityColorNeutralNeutral100Opacity25 = Color(0x40f5f5f5);

  static const opacityColorNeutralNeutral100Opacity30 = Color(0x4df5f5f5);

  static const opacityColorNeutralNeutral100Opacity35 = Color(0x59f5f5f5);

  static const opacityColorNeutralNeutral100Opacity40 = Color(0x66f5f5f5);

  static const opacityColorNeutralNeutral100Opacity45 = Color(0x73f5f5f5);

  static const opacityColorNeutralNeutral100Opacity5 = Color(0x0df5f5f5);

  static const opacityColorNeutralNeutral100Opacity50 = Color(0x80f5f5f5);

  static const opacityColorNeutralNeutral100Opacity55 = Color(0x8cf5f5f5);

  static const opacityColorNeutralNeutral100Opacity60 = Color(0x99f5f5f5);

  static const opacityColorNeutralNeutral100Opacity65 = Color(0xa6f5f5f5);

  static const opacityColorNeutralNeutral100Opacity70 = Color(0xb2f5f5f5);

  static const opacityColorNeutralNeutral100Opacity75 = Color(0xbff5f5f5);

  static const opacityColorNeutralNeutral100Opacity80 = Color(0xccf5f5f5);

  static const opacityColorNeutralNeutral100Opacity85 = Color(0xd9f5f5f5);

  static const opacityColorNeutralNeutral100Opacity90 = Color(0xe5f5f5f5);

  static const opacityColorNeutralNeutral100Opacity95 = Color(0xf2f5f5f5);

  static const opacityColorNeutralNeutral800Opacity0 = Color(0x00262626);

  static const opacityColorNeutralNeutral800Opacity10 = Color(0x1a262626);

  static const opacityColorNeutralNeutral800Opacity100 = Color(0xff262626);

  static const opacityColorNeutralNeutral800Opacity15 = Color(0x26262626);

  static const opacityColorNeutralNeutral800Opacity20 = Color(0x33262626);

  static const opacityColorNeutralNeutral800Opacity25 = Color(0x40262626);

  static const opacityColorNeutralNeutral800Opacity30 = Color(0x4d262626);

  static const opacityColorNeutralNeutral800Opacity35 = Color(0x59262626);

  static const opacityColorNeutralNeutral800Opacity40 = Color(0x66262626);

  static const opacityColorNeutralNeutral800Opacity45 = Color(0x73262626);

  static const opacityColorNeutralNeutral800Opacity5 = Color(0x0d262626);

  static const opacityColorNeutralNeutral800Opacity50 = Color(0x80262626);

  static const opacityColorNeutralNeutral800Opacity55 = Color(0x8c262626);

  static const opacityColorNeutralNeutral800Opacity60 = Color(0x99262626);

  static const opacityColorNeutralNeutral800Opacity65 = Color(0xa6262626);

  static const opacityColorNeutralNeutral800Opacity70 = Color(0xb2262626);

  static const opacityColorNeutralNeutral800Opacity75 = Color(0xbf262626);

  static const opacityColorNeutralNeutral800Opacity80 = Color(0xcc262626);

  static const opacityColorNeutralNeutral800Opacity85 = Color(0xd9262626);

  static const opacityColorNeutralNeutral800Opacity90 = Color(0xe5262626);

  static const opacityColorNeutralNeutral800Opacity95 = Color(0xf2262626);

  static const opacityColorNeutralNeutral950Opacity0 = Color(0x000a0a0a);

  static const opacityColorNeutralNeutral950Opacity10 = Color(0x1a0a0a0a);

  static const opacityColorNeutralNeutral950Opacity100 = Color(0xff0a0a0a);

  static const opacityColorNeutralNeutral950Opacity15 = Color(0x260a0a0a);

  static const opacityColorNeutralNeutral950Opacity20 = Color(0x330a0a0a);

  static const opacityColorNeutralNeutral950Opacity25 = Color(0x400a0a0a);

  static const opacityColorNeutralNeutral950Opacity30 = Color(0x4d0a0a0a);

  static const opacityColorNeutralNeutral950Opacity35 = Color(0x590a0a0a);

  static const opacityColorNeutralNeutral950Opacity40 = Color(0x660a0a0a);

  static const opacityColorNeutralNeutral950Opacity45 = Color(0x730a0a0a);

  static const opacityColorNeutralNeutral950Opacity5 = Color(0x0d0a0a0a);

  static const opacityColorNeutralNeutral950Opacity50 = Color(0x800a0a0a);

  static const opacityColorNeutralNeutral950Opacity55 = Color(0x8c0a0a0a);

  static const opacityColorNeutralNeutral950Opacity60 = Color(0x990a0a0a);

  static const opacityColorNeutralNeutral950Opacity65 = Color(0xa60a0a0a);

  static const opacityColorNeutralNeutral950Opacity70 = Color(0xb20a0a0a);

  static const opacityColorNeutralNeutral950Opacity75 = Color(0xbf0a0a0a);

  static const opacityColorNeutralNeutral950Opacity80 = Color(0xcc0a0a0a);

  static const opacityColorNeutralNeutral950Opacity85 = Color(0xd90a0a0a);

  static const opacityColorNeutralNeutral950Opacity90 = Color(0xe50a0a0a);

  static const opacityColorNeutralNeutral950Opacity95 = Color(0xf20a0a0a);

  static const opacityColorNeutralWhiteOpacity0 = Color(0x00ffffff);

  static const opacityColorNeutralWhiteOpacity10 = Color(0x1affffff);

  static const opacityColorNeutralWhiteOpacity100 = Color(0xffffffff);

  static const opacityColorNeutralWhiteOpacity15 = Color(0x26ffffff);

  static const opacityColorNeutralWhiteOpacity20 = Color(0x33ffffff);

  static const opacityColorNeutralWhiteOpacity25 = Color(0x40ffffff);

  static const opacityColorNeutralWhiteOpacity30 = Color(0x4dffffff);

  static const opacityColorNeutralWhiteOpacity35 = Color(0x59ffffff);

  static const opacityColorNeutralWhiteOpacity40 = Color(0x66ffffff);

  static const opacityColorNeutralWhiteOpacity45 = Color(0x73ffffff);

  static const opacityColorNeutralWhiteOpacity5 = Color(0x0dffffff);

  static const opacityColorNeutralWhiteOpacity50 = Color(0x80ffffff);

  static const opacityColorNeutralWhiteOpacity55 = Color(0x8cffffff);

  static const opacityColorNeutralWhiteOpacity60 = Color(0x99ffffff);

  static const opacityColorNeutralWhiteOpacity65 = Color(0xa6ffffff);

  static const opacityColorNeutralWhiteOpacity70 = Color(0xb2ffffff);

  static const opacityColorNeutralWhiteOpacity75 = Color(0xbfffffff);

  static const opacityColorNeutralWhiteOpacity80 = Color(0xccffffff);

  static const opacityColorNeutralWhiteOpacity85 = Color(0xd9ffffff);

  static const opacityColorNeutralWhiteOpacity90 = Color(0xe5ffffff);

  static const opacityColorNeutralWhiteOpacity95 = Color(0xf2ffffff);

  static const opacityColorSystemGreenGreen100Opacity0 = Color(0x00dcfce7);

  static const opacityColorSystemGreenGreen100Opacity10 = Color(0x1adcfce7);

  static const opacityColorSystemGreenGreen100Opacity100 = Color(0xffdcfce7);

  static const opacityColorSystemGreenGreen100Opacity15 = Color(0x26dcfce7);

  static const opacityColorSystemGreenGreen100Opacity20 = Color(0x33dcfce7);

  static const opacityColorSystemGreenGreen100Opacity25 = Color(0x40dcfce7);

  static const opacityColorSystemGreenGreen100Opacity30 = Color(0x4ddcfce7);

  static const opacityColorSystemGreenGreen100Opacity35 = Color(0x59dcfce7);

  static const opacityColorSystemGreenGreen100Opacity40 = Color(0x66dcfce7);

  static const opacityColorSystemGreenGreen100Opacity45 = Color(0x73dcfce7);

  static const opacityColorSystemGreenGreen100Opacity5 = Color(0x0ddcfce7);

  static const opacityColorSystemGreenGreen100Opacity50 = Color(0x80dcfce7);

  static const opacityColorSystemGreenGreen100Opacity55 = Color(0x8cdcfce7);

  static const opacityColorSystemGreenGreen100Opacity60 = Color(0x99dcfce7);

  static const opacityColorSystemGreenGreen100Opacity65 = Color(0xa6dcfce7);

  static const opacityColorSystemGreenGreen100Opacity70 = Color(0xb2dcfce7);

  static const opacityColorSystemGreenGreen100Opacity75 = Color(0xbfdcfce7);

  static const opacityColorSystemGreenGreen100Opacity80 = Color(0xccdcfce7);

  static const opacityColorSystemGreenGreen100Opacity85 = Color(0xd9dcfce7);

  static const opacityColorSystemGreenGreen100Opacity90 = Color(0xe5dcfce7);

  static const opacityColorSystemGreenGreen100Opacity95 = Color(0xf2dcfce7);

  static const opacityColorSystemGreenGreen500Opacity0 = Color(0x0000c950);

  static const opacityColorSystemGreenGreen500Opacity10 = Color(0x1a00c950);

  static const opacityColorSystemGreenGreen500Opacity100 = Color(0xff00c950);

  static const opacityColorSystemGreenGreen500Opacity15 = Color(0x2600c950);

  static const opacityColorSystemGreenGreen500Opacity20 = Color(0x3300c950);

  static const opacityColorSystemGreenGreen500Opacity25 = Color(0x4000c950);

  static const opacityColorSystemGreenGreen500Opacity30 = Color(0x4d00c950);

  static const opacityColorSystemGreenGreen500Opacity35 = Color(0x5900c950);

  static const opacityColorSystemGreenGreen500Opacity40 = Color(0x6600c950);

  static const opacityColorSystemGreenGreen500Opacity45 = Color(0x7300c950);

  static const opacityColorSystemGreenGreen500Opacity5 = Color(0x0d00c950);

  static const opacityColorSystemGreenGreen500Opacity50 = Color(0x8000c950);

  static const opacityColorSystemGreenGreen500Opacity55 = Color(0x8c00c950);

  static const opacityColorSystemGreenGreen500Opacity60 = Color(0x9900c950);

  static const opacityColorSystemGreenGreen500Opacity65 = Color(0xa600c950);

  static const opacityColorSystemGreenGreen500Opacity70 = Color(0xb200c950);

  static const opacityColorSystemGreenGreen500Opacity75 = Color(0xbf00c950);

  static const opacityColorSystemGreenGreen500Opacity80 = Color(0xcc00c950);

  static const opacityColorSystemGreenGreen500Opacity85 = Color(0xd900c950);

  static const opacityColorSystemGreenGreen500Opacity90 = Color(0xe500c950);

  static const opacityColorSystemGreenGreen500Opacity95 = Color(0xf200c950);

  static const opacityColorSystemGreenGreen600Opacity0 = Color(0x0000a63e);

  static const opacityColorSystemGreenGreen600Opacity10 = Color(0x1a00a63e);

  static const opacityColorSystemGreenGreen600Opacity100 = Color(0xff00a63e);

  static const opacityColorSystemGreenGreen600Opacity15 = Color(0x2600a63e);

  static const opacityColorSystemGreenGreen600Opacity20 = Color(0x3300a63e);

  static const opacityColorSystemGreenGreen600Opacity25 = Color(0x4000a63e);

  static const opacityColorSystemGreenGreen600Opacity30 = Color(0x4d00a63e);

  static const opacityColorSystemGreenGreen600Opacity35 = Color(0x5900a63e);

  static const opacityColorSystemGreenGreen600Opacity40 = Color(0x6600a63e);

  static const opacityColorSystemGreenGreen600Opacity45 = Color(0x7300a63e);

  static const opacityColorSystemGreenGreen600Opacity5 = Color(0x0d00a63e);

  static const opacityColorSystemGreenGreen600Opacity50 = Color(0x8000a63e);

  static const opacityColorSystemGreenGreen600Opacity55 = Color(0x8c00a63e);

  static const opacityColorSystemGreenGreen600Opacity60 = Color(0x9900a63e);

  static const opacityColorSystemGreenGreen600Opacity65 = Color(0xa600a63e);

  static const opacityColorSystemGreenGreen600Opacity70 = Color(0xb200a63e);

  static const opacityColorSystemGreenGreen600Opacity75 = Color(0xbf00a63e);

  static const opacityColorSystemGreenGreen600Opacity80 = Color(0xcc00a63e);

  static const opacityColorSystemGreenGreen600Opacity85 = Color(0xd900a63e);

  static const opacityColorSystemGreenGreen600Opacity90 = Color(0xe500a63e);

  static const opacityColorSystemGreenGreen600Opacity95 = Color(0xf200a63e);

  static const opacityColorSystemGreenGreen700Opacity0 = Color(0x00008236);

  static const opacityColorSystemGreenGreen700Opacity10 = Color(0x1a008236);

  static const opacityColorSystemGreenGreen700Opacity100 = Color(0xff008236);

  static const opacityColorSystemGreenGreen700Opacity15 = Color(0x26008236);

  static const opacityColorSystemGreenGreen700Opacity20 = Color(0x33008236);

  static const opacityColorSystemGreenGreen700Opacity25 = Color(0x40008236);

  static const opacityColorSystemGreenGreen700Opacity30 = Color(0x4d008236);

  static const opacityColorSystemGreenGreen700Opacity35 = Color(0x59008236);

  static const opacityColorSystemGreenGreen700Opacity40 = Color(0x66008236);

  static const opacityColorSystemGreenGreen700Opacity45 = Color(0x73008236);

  static const opacityColorSystemGreenGreen700Opacity5 = Color(0x0d008236);

  static const opacityColorSystemGreenGreen700Opacity50 = Color(0x80008236);

  static const opacityColorSystemGreenGreen700Opacity55 = Color(0x8c008236);

  static const opacityColorSystemGreenGreen700Opacity60 = Color(0x99008236);

  static const opacityColorSystemGreenGreen700Opacity65 = Color(0xa6008236);

  static const opacityColorSystemGreenGreen700Opacity70 = Color(0xb2008236);

  static const opacityColorSystemGreenGreen700Opacity75 = Color(0xbf008236);

  static const opacityColorSystemGreenGreen700Opacity80 = Color(0xcc008236);

  static const opacityColorSystemGreenGreen700Opacity85 = Color(0xd9008236);

  static const opacityColorSystemGreenGreen700Opacity90 = Color(0xe5008236);

  static const opacityColorSystemGreenGreen700Opacity95 = Color(0xf2008236);

  static const opacityColorSystemOrangeOrange100Opacity0 = Color(0x00ffedd4);

  static const opacityColorSystemOrangeOrange100Opacity10 = Color(0x1affedd4);

  static const opacityColorSystemOrangeOrange100Opacity100 = Color(0xffffedd4);

  static const opacityColorSystemOrangeOrange100Opacity15 = Color(0x26ffedd4);

  static const opacityColorSystemOrangeOrange100Opacity20 = Color(0x33ffedd4);

  static const opacityColorSystemOrangeOrange100Opacity25 = Color(0x40ffedd4);

  static const opacityColorSystemOrangeOrange100Opacity30 = Color(0x4dffedd4);

  static const opacityColorSystemOrangeOrange100Opacity35 = Color(0x59ffedd4);

  static const opacityColorSystemOrangeOrange100Opacity40 = Color(0x66ffedd4);

  static const opacityColorSystemOrangeOrange100Opacity45 = Color(0x73ffedd4);

  static const opacityColorSystemOrangeOrange100Opacity5 = Color(0x0dffedd4);

  static const opacityColorSystemOrangeOrange100Opacity50 = Color(0x80ffedd4);

  static const opacityColorSystemOrangeOrange100Opacity55 = Color(0x8cffedd4);

  static const opacityColorSystemOrangeOrange100Opacity60 = Color(0x99ffedd4);

  static const opacityColorSystemOrangeOrange100Opacity65 = Color(0xa6ffedd4);

  static const opacityColorSystemOrangeOrange100Opacity70 = Color(0xb2ffedd4);

  static const opacityColorSystemOrangeOrange100Opacity75 = Color(0xbfffedd4);

  static const opacityColorSystemOrangeOrange100Opacity80 = Color(0xccffedd4);

  static const opacityColorSystemOrangeOrange100Opacity85 = Color(0xd9ffedd4);

  static const opacityColorSystemOrangeOrange100Opacity90 = Color(0xe5ffedd4);

  static const opacityColorSystemOrangeOrange100Opacity95 = Color(0xf2ffedd4);

  static const opacityColorSystemOrangeOrange300Opacity0 = Color(0x00ffb86a);

  static const opacityColorSystemOrangeOrange300Opacity10 = Color(0x1affb86a);

  static const opacityColorSystemOrangeOrange300Opacity100 = Color(0xffffb86a);

  static const opacityColorSystemOrangeOrange300Opacity15 = Color(0x26ffb86a);

  static const opacityColorSystemOrangeOrange300Opacity20 = Color(0x33ffb86a);

  static const opacityColorSystemOrangeOrange300Opacity25 = Color(0x40ffb86a);

  static const opacityColorSystemOrangeOrange300Opacity30 = Color(0x4dffb86a);

  static const opacityColorSystemOrangeOrange300Opacity35 = Color(0x59ffb86a);

  static const opacityColorSystemOrangeOrange300Opacity40 = Color(0x66ffb86a);

  static const opacityColorSystemOrangeOrange300Opacity45 = Color(0x73ffb86a);

  static const opacityColorSystemOrangeOrange300Opacity5 = Color(0x0dffb86a);

  static const opacityColorSystemOrangeOrange300Opacity50 = Color(0x80ffb86a);

  static const opacityColorSystemOrangeOrange300Opacity55 = Color(0x8cffb86a);

  static const opacityColorSystemOrangeOrange300Opacity60 = Color(0x99ffb86a);

  static const opacityColorSystemOrangeOrange300Opacity65 = Color(0xa6ffb86a);

  static const opacityColorSystemOrangeOrange300Opacity70 = Color(0xb2ffb86a);

  static const opacityColorSystemOrangeOrange300Opacity75 = Color(0xbfffb86a);

  static const opacityColorSystemOrangeOrange300Opacity80 = Color(0xccffb86a);

  static const opacityColorSystemOrangeOrange300Opacity85 = Color(0xd9ffb86a);

  static const opacityColorSystemOrangeOrange300Opacity90 = Color(0xe5ffb86a);

  static const opacityColorSystemOrangeOrange300Opacity95 = Color(0xf2ffb86a);

  static const opacityColorSystemOrangeOrange400Opacity0 = Color(0x00ff8904);

  static const opacityColorSystemOrangeOrange400Opacity10 = Color(0x1aff8904);

  static const opacityColorSystemOrangeOrange400Opacity100 = Color(0xffff8904);

  static const opacityColorSystemOrangeOrange400Opacity15 = Color(0x26ff8904);

  static const opacityColorSystemOrangeOrange400Opacity20 = Color(0x33ff8904);

  static const opacityColorSystemOrangeOrange400Opacity25 = Color(0x40ff8904);

  static const opacityColorSystemOrangeOrange400Opacity30 = Color(0x4dff8904);

  static const opacityColorSystemOrangeOrange400Opacity35 = Color(0x59ff8904);

  static const opacityColorSystemOrangeOrange400Opacity40 = Color(0x66ff8904);

  static const opacityColorSystemOrangeOrange400Opacity45 = Color(0x73ff8904);

  static const opacityColorSystemOrangeOrange400Opacity5 = Color(0x0dff8904);

  static const opacityColorSystemOrangeOrange400Opacity50 = Color(0x80ff8904);

  static const opacityColorSystemOrangeOrange400Opacity55 = Color(0x8cff8904);

  static const opacityColorSystemOrangeOrange400Opacity60 = Color(0x99ff8904);

  static const opacityColorSystemOrangeOrange400Opacity65 = Color(0xa6ff8904);

  static const opacityColorSystemOrangeOrange400Opacity70 = Color(0xb2ff8904);

  static const opacityColorSystemOrangeOrange400Opacity75 = Color(0xbfff8904);

  static const opacityColorSystemOrangeOrange400Opacity80 = Color(0xccff8904);

  static const opacityColorSystemOrangeOrange400Opacity85 = Color(0xd9ff8904);

  static const opacityColorSystemOrangeOrange400Opacity90 = Color(0xe5ff8904);

  static const opacityColorSystemOrangeOrange400Opacity95 = Color(0xf2ff8904);

  static const opacityColorSystemRedRed100Opacity0 = Color(0x00ffe2e2);

  static const opacityColorSystemRedRed100Opacity10 = Color(0x1affe2e2);

  static const opacityColorSystemRedRed100Opacity100 = Color(0xffffe2e2);

  static const opacityColorSystemRedRed100Opacity15 = Color(0x26ffe2e2);

  static const opacityColorSystemRedRed100Opacity20 = Color(0x33ffe2e2);

  static const opacityColorSystemRedRed100Opacity25 = Color(0x40ffe2e2);

  static const opacityColorSystemRedRed100Opacity30 = Color(0x4dffe2e2);

  static const opacityColorSystemRedRed100Opacity35 = Color(0x59ffe2e2);

  static const opacityColorSystemRedRed100Opacity40 = Color(0x66ffe2e2);

  static const opacityColorSystemRedRed100Opacity45 = Color(0x73ffe2e2);

  static const opacityColorSystemRedRed100Opacity5 = Color(0x0dffe2e2);

  static const opacityColorSystemRedRed100Opacity50 = Color(0x80ffe2e2);

  static const opacityColorSystemRedRed100Opacity55 = Color(0x8cffe2e2);

  static const opacityColorSystemRedRed100Opacity60 = Color(0x99ffe2e2);

  static const opacityColorSystemRedRed100Opacity65 = Color(0xa6ffe2e2);

  static const opacityColorSystemRedRed100Opacity70 = Color(0xb2ffe2e2);

  static const opacityColorSystemRedRed100Opacity75 = Color(0xbfffe2e2);

  static const opacityColorSystemRedRed100Opacity80 = Color(0xccffe2e2);

  static const opacityColorSystemRedRed100Opacity85 = Color(0xd9ffe2e2);

  static const opacityColorSystemRedRed100Opacity90 = Color(0xe5ffe2e2);

  static const opacityColorSystemRedRed100Opacity95 = Color(0xf2ffe2e2);

  static const opacityColorSystemRedRed500Opacity0 = Color(0x00fb2c36);

  static const opacityColorSystemRedRed500Opacity10 = Color(0x1afb2c36);

  static const opacityColorSystemRedRed500Opacity100 = Color(0xfffb2c36);

  static const opacityColorSystemRedRed500Opacity15 = Color(0x26fb2c36);

  static const opacityColorSystemRedRed500Opacity20 = Color(0x33fb2c36);

  static const opacityColorSystemRedRed500Opacity25 = Color(0x40fb2c36);

  static const opacityColorSystemRedRed500Opacity30 = Color(0x4dfb2c36);

  static const opacityColorSystemRedRed500Opacity35 = Color(0x59fb2c36);

  static const opacityColorSystemRedRed500Opacity40 = Color(0x66fb2c36);

  static const opacityColorSystemRedRed500Opacity45 = Color(0x73fb2c36);

  static const opacityColorSystemRedRed500Opacity5 = Color(0x0dfb2c36);

  static const opacityColorSystemRedRed500Opacity50 = Color(0x80fb2c36);

  static const opacityColorSystemRedRed500Opacity55 = Color(0x8cfb2c36);

  static const opacityColorSystemRedRed500Opacity60 = Color(0x99fb2c36);

  static const opacityColorSystemRedRed500Opacity65 = Color(0xa6fb2c36);

  static const opacityColorSystemRedRed500Opacity70 = Color(0xb2fb2c36);

  static const opacityColorSystemRedRed500Opacity75 = Color(0xbffb2c36);

  static const opacityColorSystemRedRed500Opacity80 = Color(0xccfb2c36);

  static const opacityColorSystemRedRed500Opacity85 = Color(0xd9fb2c36);

  static const opacityColorSystemRedRed500Opacity90 = Color(0xe5fb2c36);

  static const opacityColorSystemRedRed500Opacity95 = Color(0xf2fb2c36);

  static const opacityColorSystemRedRed600Opacity0 = Color(0x00e7000b);

  static const opacityColorSystemRedRed600Opacity10 = Color(0x1ae7000b);

  static const opacityColorSystemRedRed600Opacity100 = Color(0xffe7000b);

  static const opacityColorSystemRedRed600Opacity15 = Color(0x26e7000b);

  static const opacityColorSystemRedRed600Opacity20 = Color(0x33e7000b);

  static const opacityColorSystemRedRed600Opacity25 = Color(0x40e7000b);

  static const opacityColorSystemRedRed600Opacity30 = Color(0x4de7000b);

  static const opacityColorSystemRedRed600Opacity35 = Color(0x59e7000b);

  static const opacityColorSystemRedRed600Opacity40 = Color(0x66e7000b);

  static const opacityColorSystemRedRed600Opacity45 = Color(0x73e7000b);

  static const opacityColorSystemRedRed600Opacity5 = Color(0x0de7000b);

  static const opacityColorSystemRedRed600Opacity50 = Color(0x80e7000b);

  static const opacityColorSystemRedRed600Opacity55 = Color(0x8ce7000b);

  static const opacityColorSystemRedRed600Opacity60 = Color(0x99e7000b);

  static const opacityColorSystemRedRed600Opacity65 = Color(0xa6e7000b);

  static const opacityColorSystemRedRed600Opacity70 = Color(0xb2e7000b);

  static const opacityColorSystemRedRed600Opacity75 = Color(0xbfe7000b);

  static const opacityColorSystemRedRed600Opacity80 = Color(0xcce7000b);

  static const opacityColorSystemRedRed600Opacity85 = Color(0xd9e7000b);

  static const opacityColorSystemRedRed600Opacity90 = Color(0xe5e7000b);

  static const opacityColorSystemRedRed600Opacity95 = Color(0xf2e7000b);

  PepperCoreColors._();
}

/// Semantic, component, static, state, and overlay colours. Use these in product code.
/// Dark-mode values are documented in doc comments; the live value depends on your theme switcher.
class PepperColors {
  /// Dark-mode value: #0165fa1a
  static const colorBgOverlayHighlightBrandPrimary = Color(0x593484fb);

  /// Dark-mode value: #3484fb59
  static const colorBgOverlayHighlightInverseBrandPrimary = Color(0x1a0165fa);

  /// Dark-mode value: #0a0a0a0d
  static const colorBgOverlayHighlightInverseTonalPrimary = Color(0x33f5f5f5);

  /// Dark-mode value: #ffffff33
  static const colorBgOverlayHighlightTonalPrimary = Color(0x0d0a0a0a);

  /// Dark-mode value: #3484fb
  static const colorBgSurfaceAccentBlueStrong = Color(0xff0165fa);

  /// Dark-mode value: #000061
  static const colorBgSurfaceAccentBlueSubtle = Color(0xffe6f0ff);

  /// Dark-mode value: #53eafd
  static const colorBgSurfaceAccentCyanStrong = Color(0xff00d3f3);

  /// Dark-mode value: #053345
  static const colorBgSurfaceAccentCyanSubtle = Color(0xffcefafe);

  /// Dark-mode value: #00c950
  static const colorBgSurfaceAccentGreenStrong = Color(0xff00a63e);

  /// Dark-mode value: #032e15
  static const colorBgSurfaceAccentGreenSubtle = Color(0xffdcfce7);

  /// Dark-mode value: #82b536
  static const colorBgSurfaceAccentLimeStrong = Color(0xff94c748);

  /// Dark-mode value: #1a2e05
  static const colorBgSurfaceAccentLimeSubtle = Color(0xffd3f1a7);

  /// Dark-mode value: #da62ac
  static const colorBgSurfaceAccentMagentaStrong = Color(0xffe774bb);

  /// Dark-mode value: #500724
  static const colorBgSurfaceAccentMagentaSubtle = Color(0xfffdd0ec);

  /// Dark-mode value: #ffb86a
  static const colorBgSurfaceAccentOrangeStrong = Color(0xffff8904);

  /// Dark-mode value: #441306
  static const colorBgSurfaceAccentOrangeSubtle = Color(0xffffedd4);

  /// Dark-mode value: #fb2c36
  static const colorBgSurfaceAccentRedStrong = Color(0xffe7000b);

  /// Dark-mode value: #460809
  static const colorBgSurfaceAccentRedSubtle = Color(0xffffe2e2);

  /// Dark-mode value: #ffffffcc
  static const colorBgSurfaceAccentTonalStrong = Color(0x990a0a0a);

  /// Dark-mode value: #ffffff4d
  static const colorBgSurfaceAccentTonalSubtle = Color(0x1a0a0a0a);

  /// Dark-mode value: #3ac190
  static const colorBgSurfaceAccentTurquoiseStrong = Color(0xff47e0a8);

  /// Dark-mode value: #134e4a
  static const colorBgSurfaceAccentTurquoiseSubtle = Color(0xffd7f9ed);

  /// Dark-mode value: #7f00ad
  static const colorBgSurfaceAccentVioletStrong = Color(0xffaa30d8);

  /// Dark-mode value: #260333
  static const colorBgSurfaceAccentVioletSubtle = Color(0xffe3c0f0);

  /// Dark-mode value: #ddb30e
  static const colorBgSurfaceAccentYellowStrong = Color(0xffeed12b);

  /// Dark-mode value: #451a03
  static const colorBgSurfaceAccentYellowSubtle = Color(0xfffef7c8);

  static const colorBgSurfaceBrandCrypto = Color(0xffff5000);

  static const colorBgSurfaceBrandCryptoHover = Color(0xffcc3702);

  static const colorBgSurfaceBrandPrimary = Color(0xff0165fa);

  static const colorBgSurfaceBrandPrimaryHover = Color(0xff0032c7);

  static const colorBgSurfaceBrandSecondary = Color(0xff00d3f3);

  static const colorBgSurfaceBrandSecondaryHover = Color(0xff00b8db);

  /// Dark-mode value: #000061
  static const colorBgSurfaceBrandSubtle = Color(0xffe6f0ff);

  /// Dark-mode value: #000094
  static const colorBgSurfaceBrandSubtleHover = Color(0xff99c1fd);

  /// Dark-mode value: #ffffff33
  static const colorBgSurfaceDisabled = Color(0x1a0a0a0a);

  /// Dark-mode value: #262626
  static const colorBgSurfaceElevated = Color(0xffffffff);

  /// Dark-mode value: #0165fa
  static const colorBgSurfaceInverseAccentBlueStrong = Color(0xff3484fb);

  /// Dark-mode value: #e6f0ff
  static const colorBgSurfaceInverseAccentBlueSubtle = Color(0xff000061);

  /// Dark-mode value: #00d3f3
  static const colorBgSurfaceInverseAccentCyanStrong = Color(0xff53eafd);

  /// Dark-mode value: #cefafe
  static const colorBgSurfaceInverseAccentCyanSubtle = Color(0xff053345);

  /// Dark-mode value: #00a63e
  static const colorBgSurfaceInverseAccentGreenStrong = Color(0xff00c950);

  /// Dark-mode value: #dcfce7
  static const colorBgSurfaceInverseAccentGreenSubtle = Color(0xff032e15);

  /// Dark-mode value: #94c748
  static const colorBgSurfaceInverseAccentLimeStrong = Color(0xff82b536);

  /// Dark-mode value: #d3f1a7
  static const colorBgSurfaceInverseAccentLimeSubtle = Color(0xff1a2e05);

  /// Dark-mode value: #e774bb
  static const colorBgSurfaceInverseAccentMagentaStrong = Color(0xffda62ac);

  /// Dark-mode value: #fdd0ec
  static const colorBgSurfaceInverseAccentMagentaSubtle = Color(0xff500724);

  /// Dark-mode value: #ff8904
  static const colorBgSurfaceInverseAccentOrangeStrong = Color(0xffff6900);

  /// Dark-mode value: #ffedd4
  static const colorBgSurfaceInverseAccentOrangeSubtle = Color(0xff441306);

  /// Dark-mode value: #e7000b
  static const colorBgSurfaceInverseAccentRedStrong = Color(0xfffb2c36);

  /// Dark-mode value: #ffe2e2
  static const colorBgSurfaceInverseAccentRedSubtle = Color(0xff460809);

  /// Dark-mode value: #0a0a0a99
  static const colorBgSurfaceInverseAccentTonalStrong = Color(0xccffffff);

  /// Dark-mode value: #0a0a0a1a
  static const colorBgSurfaceInverseAccentTonalSubtle = Color(0x4dffffff);

  /// Dark-mode value: #47e0a8
  static const colorBgSurfaceInverseAccentTurquoiseStrong = Color(0xff3ac190);

  /// Dark-mode value: #d7f9ed
  static const colorBgSurfaceInverseAccentTurquoiseSubtle = Color(0xff134e4a);

  /// Dark-mode value: #aa30d8
  static const colorBgSurfaceInverseAccentVioletStrong = Color(0xff7f00ad);

  /// Dark-mode value: #e3c0f0
  static const colorBgSurfaceInverseAccentVioletSubtle = Color(0xff260333);

  static const colorBgSurfaceInverseAccentYellowStrong = Color(0xffddb30e);

  /// Dark-mode value: #fef7c8
  static const colorBgSurfaceInverseAccentYellowSubtle = Color(0xff451a03);

  static const colorBgSurfaceInverseBrandCrypto = Color(0xffff5000);

  static const colorBgSurfaceInverseBrandCryptoHover = Color(0xffcc3702);

  static const colorBgSurfaceInverseBrandPrimary = Color(0xff0165fa);

  static const colorBgSurfaceInverseBrandPrimaryHover = Color(0xff0032c7);

  static const colorBgSurfaceInverseBrandSecondary = Color(0xff00d3f3);

  static const colorBgSurfaceInverseBrandSecondaryHover = Color(0xff00b8db);

  /// Dark-mode value: #e6f0ff
  static const colorBgSurfaceInverseBrandSubtle = Color(0xff000061);

  /// Dark-mode value: #99c1fd
  static const colorBgSurfaceInverseBrandSubtleHover = Color(0xff000094);

  /// Dark-mode value: #0a0a0a1a
  static const colorBgSurfaceInverseDisabled = Color(0x33ffffff);

  /// Dark-mode value: #ffffff
  static const colorBgSurfaceInverseElevated = Color(0xff0a0a0a);

  /// Dark-mode value: #e7000b
  static const colorBgSurfaceInverseNegative = Color(0xfffb2c36);

  /// Dark-mode value: #c10007
  static const colorBgSurfaceInverseNegativeHover = Color(0xffff6467);

  /// Dark-mode value: #008236
  static const colorBgSurfaceInversePositive = Color(0xff00c950);

  /// Dark-mode value: #016630
  static const colorBgSurfaceInversePositiveHover = Color(0xff05df72);

  /// Dark-mode value: #ffffff
  static const colorBgSurfaceInversePrimary = Color(0xff0a0a0a);

  /// Dark-mode value: #f5f5f5
  static const colorBgSurfaceInversePrimaryHover = Color(0xff262626);

  /// Dark-mode value: #f5f5f5
  static const colorBgSurfaceInverseSecondary = Color(0xff262626);

  /// Dark-mode value: #e5e5e5
  static const colorBgSurfaceInverseSecondaryHover = Color(0xff404040);

  static const colorBgSurfaceInverseSunken = Color(0xff262626);

  /// Dark-mode value: #ffe2e2
  static const colorBgSurfaceInverseSystemError = Color(0xff460809);

  /// Dark-mode value: #dcfce7
  static const colorBgSurfaceInverseSystemSuccess = Color(0xff032e15);

  /// Dark-mode value: #ffedd4
  static const colorBgSurfaceInverseSystemWarning = Color(0xff441306);

  /// Dark-mode value: #ffffff00
  static const colorBgSurfaceInverseTransparent = Color(0x000a0a0a);

  /// Dark-mode value: #fb2c36
  static const colorBgSurfaceNegative = Color(0xffe7000b);

  /// Dark-mode value: #ff6467
  static const colorBgSurfaceNegativeHover = Color(0xffc10007);

  /// Dark-mode value: #00c950
  static const colorBgSurfacePositive = Color(0xff008236);

  /// Dark-mode value: #05df72
  static const colorBgSurfacePositiveHover = Color(0xff016630);

  /// Dark-mode value: #0a0a0a
  static const colorBgSurfacePrimary = Color(0xffffffff);

  /// Dark-mode value: #262626
  static const colorBgSurfacePrimaryHover = Color(0xfff5f5f5);

  /// Dark-mode value: #262626
  static const colorBgSurfaceSecondary = Color(0xfff5f5f5);

  /// Dark-mode value: #404040
  static const colorBgSurfaceSecondaryHover = Color(0xffe5e5e5);

  /// Dark-mode value: #0a0a0a
  static const colorBgSurfaceSunken = Color(0xfff5f5f5);

  /// Dark-mode value: #460809
  static const colorBgSurfaceSystemError = Color(0xffffe2e2);

  /// Dark-mode value: #032e15
  static const colorBgSurfaceSystemSuccess = Color(0xffdcfce7);

  /// Dark-mode value: #441306
  static const colorBgSurfaceSystemWarning = Color(0xffffedd4);

  /// Dark-mode value: #0a0a0a00
  static const colorBgSurfaceTransparent = Color(0x00ffffff);

  /// Dark-mode value: #00a63e33
  static const colorComponentBuysellButtonBgBuyBlur = Color(0x33008236);

  /// Dark-mode value: #00c950
  static const colorComponentBuysellButtonBgBuyDefault = Color(0xff008236);

  /// Dark-mode value: #05df72
  static const colorComponentBuysellButtonBgBuyHover = Color(0xff016630);

  /// Dark-mode value: #e7000b33
  static const colorComponentBuysellButtonBgSellBlur = Color(0x33fb2c36);

  /// Dark-mode value: #fb2c36
  static const colorComponentBuysellButtonBgSellDefault = Color(0xffe7000b);

  /// Dark-mode value: #ff6467
  static const colorComponentBuysellButtonBgSellHover = Color(0xffc10007);

  static const colorComponentInputStrokeActive = Color(0xff0a0a0a);

  static const colorComponentInputStrokeDefault = Color(0xffd4d4d4);

  static const colorComponentInputSurface = Color(0xffffffff);

  /// Dark-mode value: #00c950
  static const colorFgEffectsGradientSurfaceAccentGreenFull = Color(0xff008236);

  /// Dark-mode value: #00c95000
  static const colorFgEffectsGradientSurfaceAccentGreenNone = Color(0x00008236);

  /// Dark-mode value: #fb2c36
  static const colorFgEffectsGradientSurfaceAccentRedFull = Color(0xffe7000b);

  /// Dark-mode value: #fb2c3600
  static const colorFgEffectsGradientSurfaceAccentRedNone = Color(0x00e7000b);

  static const colorFgEffectsGradientSurfaceBrandPrimaryFull = Color(0xff0165fa);

  static const colorFgEffectsGradientSurfaceBrandPrimaryNone = Color(0x000165fa);

  /// Dark-mode value: #ffffff
  static const colorFgEffectsGradientSurfaceInversePrimaryFull = Color(0xff0a0a0a);

  /// Dark-mode value: #ffffff00
  static const colorFgEffectsGradientSurfaceInversePrimaryNone = Color(0x000a0a0a);

  /// Dark-mode value: #0a0a0a
  static const colorFgEffectsGradientSurfacePrimaryFull = Color(0xffffffff);

  /// Dark-mode value: #0a0a0a00
  static const colorFgEffectsGradientSurfacePrimaryNone = Color(0x00ffffff);

  /// Dark-mode value: #3484fb
  static const colorFgIconAccentBlueDefault = Color(0xff0165fa);

  /// Dark-mode value: #e6f0ff
  static const colorFgIconAccentBlueStrong = Color(0xff000061);

  /// Dark-mode value: #53eafd
  static const colorFgIconAccentCyanDefault = Color(0xff00d3f3);

  /// Dark-mode value: #ecfeff
  static const colorFgIconAccentCyanStrong = Color(0xff007595);

  /// Dark-mode value: #00a63e
  static const colorFgIconAccentGreenDefault = Color(0xff008236);

  /// Dark-mode value: #05df72
  static const colorFgIconAccentGreenStrong = Color(0xff0d542b);

  /// Dark-mode value: #d3f1a7
  static const colorFgIconAccentLimeDefault = Color(0xff4d7c0f);

  /// Dark-mode value: #efffd6
  static const colorFgIconAccentLimeStrong = Color(0xff1a2e05);

  /// Dark-mode value: #fdd0ec
  static const colorFgIconAccentMagentaDefault = Color(0xff9d174d);

  /// Dark-mode value: #ffecf8
  static const colorFgIconAccentMagentaStrong = Color(0xff500724);

  /// Dark-mode value: #f54900
  static const colorFgIconAccentOrangeDefault = Color(0xffca3500);

  /// Dark-mode value: #ff8904
  static const colorFgIconAccentOrangeStrong = Color(0xff7e2a0c);

  /// Dark-mode value: #fb2c36
  static const colorFgIconAccentRedDefault = Color(0xffe7000b);

  /// Dark-mode value: #ffc9c9
  static const colorFgIconAccentRedStrong = Color(0xff82181a);

  /// Dark-mode value: #d7f9ed
  static const colorFgIconAccentTurquoiseDefault = Color(0xff0d9488);

  /// Dark-mode value: #ecfcf6
  static const colorFgIconAccentTurquoiseStrong = Color(0xff134e4a);

  /// Dark-mode value: #e3c0f0
  static const colorFgIconAccentVioletDefault = Color(0xff3f144f);

  /// Dark-mode value: #fcf4ff
  static const colorFgIconAccentVioletStrong = Color(0xff260333);

  /// Dark-mode value: #f5e989
  static const colorFgIconAccentYellowDefault = Color(0xff916a00);

  /// Dark-mode value: #fef7c8
  static const colorFgIconAccentYellowStrong = Color(0xff451a03);

  /// Dark-mode value: #3484fb
  static const colorFgIconBrandDefault = Color(0xff0165fa);

  /// Dark-mode value: #53eafd
  static const colorFgIconBrandSecondaryDefault = Color(0xff00d3f3);

  /// Dark-mode value: #ecfeff
  static const colorFgIconBrandSecondaryStrong = Color(0xff053345);

  /// Dark-mode value: #e6f0ff
  static const colorFgIconBrandStrong = Color(0xff000061);

  /// Dark-mode value: #737373
  static const colorFgIconDisabled = Color(0xffa1a1a1);

  /// Dark-mode value: #0a0a0a
  static const colorFgIconInversePrimary = Color(0xffffffff);

  /// Dark-mode value: #525252
  static const colorFgIconInverseSecondary = Color(0xffa1a1a1);

  /// Dark-mode value: #fb2c36
  static const colorFgIconNegative = Color(0xffe7000b);

  /// Dark-mode value: #00a63e
  static const colorFgIconPositive = Color(0xff008236);

  /// Dark-mode value: #ffffff
  static const colorFgIconPrimary = Color(0xff0a0a0a);

  /// Dark-mode value: #a1a1a1
  static const colorFgIconSecondary = Color(0xff525252);

  /// Dark-mode value: #fb2c36
  static const colorFgIconSystemError = Color(0xffe7000b);

  /// Dark-mode value: #00a63e
  static const colorFgIconSystemSuccess = Color(0xff008236);

  /// Dark-mode value: #f54900
  static const colorFgIconSystemWarning = Color(0xffca3500);

  /// Dark-mode value: #ffffff4d
  static const colorFgStrokeAccentTonalDefault = Color(0x33000000);

  /// Dark-mode value: #3484fb
  static const colorFgStrokeBrandDefault = Color(0xff0165fa);

  /// Dark-mode value: #e6f0ff
  static const colorFgStrokeBrandStrong = Color(0xff000061);

  /// Dark-mode value: #00000033
  static const colorFgStrokeInverseAccentTonalDefault = Color(0x4dffffff);

  /// Dark-mode value: #e7000b
  static const colorFgStrokeInverseNegative = Color(0xfffb2c36);

  /// Dark-mode value: #008236
  static const colorFgStrokeInversePositive = Color(0xff00c950);

  /// Dark-mode value: #0a0a0a
  static const colorFgStrokeInverseStrong = Color(0xffffffff);

  /// Dark-mode value: #d4d4d4
  static const colorFgStrokeInverseSubtle = Color(0xff525252);

  /// Dark-mode value: #e7000b
  static const colorFgStrokeInverseSystemError = Color(0xfffb2c36);

  /// Dark-mode value: #fb2c36
  static const colorFgStrokeNegative = Color(0xffe7000b);

  /// Dark-mode value: #00c950
  static const colorFgStrokePositive = Color(0xff008236);

  /// Dark-mode value: #ffffff
  static const colorFgStrokeStrong = Color(0xff0a0a0a);

  /// Dark-mode value: #525252
  static const colorFgStrokeSubtle = Color(0xffd4d4d4);

  /// Dark-mode value: #fb2c36
  static const colorFgStrokeSystemError = Color(0xffe7000b);

  /// Dark-mode value: #3484fb
  static const colorFgTextAccentBlueDefault = Color(0xff0165fa);

  /// Dark-mode value: #e6f0ff
  static const colorFgTextAccentBlueStrong = Color(0xff000061);

  /// Dark-mode value: #53eafd
  static const colorFgTextAccentCyanDefault = Color(0xff00d3f3);

  /// Dark-mode value: #ecfeff
  static const colorFgTextAccentCyanStrong = Color(0xff007595);

  /// Dark-mode value: #00a63e
  static const colorFgTextAccentGreenDefault = Color(0xff008236);

  /// Dark-mode value: #05df72
  static const colorFgTextAccentGreenStrong = Color(0xff0d542b);

  /// Dark-mode value: #d3f1a7
  static const colorFgTextAccentLimeDefault = Color(0xff4d7c0f);

  /// Dark-mode value: #efffd6
  static const colorFgTextAccentLimeStrong = Color(0xff1a2e05);

  /// Dark-mode value: #fdd0ec
  static const colorFgTextAccentMagentaDefault = Color(0xff9d174d);

  /// Dark-mode value: #ffecf8
  static const colorFgTextAccentMagentaStrong9 = Color(0xff500724);

  /// Dark-mode value: #f54900
  static const colorFgTextAccentOrangeDefault = Color(0xffca3500);

  /// Dark-mode value: #ff8904
  static const colorFgTextAccentOrangeStrong = Color(0xff7e2a0c);

  /// Dark-mode value: #fb2c36
  static const colorFgTextAccentRedDefault = Color(0xffe7000b);

  /// Dark-mode value: #ffc9c9
  static const colorFgTextAccentRedStrong = Color(0xff82181a);

  /// Dark-mode value: #d7f9ed
  static const colorFgTextAccentTurquoiseDefault = Color(0xff0d9488);

  /// Dark-mode value: #ecfcf6
  static const colorFgTextAccentTurquoiseStrong = Color(0xff134e4a);

  /// Dark-mode value: #e3c0f0
  static const colorFgTextAccentVioletDefault = Color(0xff3f144f);

  /// Dark-mode value: #fcf4ff
  static const colorFgTextAccentVioletStrong = Color(0xff260333);

  /// Dark-mode value: #f5e989
  static const colorFgTextAccentYellowDefault = Color(0xff916a00);

  /// Dark-mode value: #fef7c8
  static const colorFgTextAccentYellowStrong = Color(0xff451a03);

  /// Dark-mode value: #3484fb
  static const colorFgTextBrandDefault = Color(0xff0165fa);

  /// Dark-mode value: #53eafd
  static const colorFgTextBrandSecondaryDefault = Color(0xff00d3f3);

  /// Dark-mode value: #ecfeff
  static const colorFgTextBrandSecondaryStrong = Color(0xff053345);

  /// Dark-mode value: #e6f0ff
  static const colorFgTextBrandStrong = Color(0xff000061);

  /// Dark-mode value: #737373
  static const colorFgTextDisabled = Color(0xffa1a1a1);

  /// Dark-mode value: #0a0a0a
  static const colorFgTextInversePrimary = Color(0xffffffff);

  /// Dark-mode value: #525252
  static const colorFgTextInverseSecondary = Color(0xffa1a1a1);

  /// Dark-mode value: #fb2c36
  static const colorFgTextNegative = Color(0xffe7000b);

  /// Dark-mode value: #00a63e
  static const colorFgTextPositive = Color(0xff008236);

  /// Dark-mode value: #ffffff
  static const colorFgTextPrimary = Color(0xff0a0a0a);

  /// Dark-mode value: #a1a1a1
  static const colorFgTextSecondary = Color(0xff525252);

  /// Dark-mode value: #fb2c36
  static const colorFgTextSystemError = Color(0xffe7000b);

  /// Dark-mode value: #00a63e
  static const colorFgTextSystemSuccess = Color(0xff008236);

  /// Dark-mode value: #f54900
  static const colorFgTextSystemWarning = Color(0xffca3500);

  static const colorStaticBadgeAlert = Color(0xfffb2c36);

  static const colorStaticBadgeBrand = Color(0xff3484fb);

  static const colorStaticDatavizError = Color(0xfffb2c36);

  static const colorStaticDatavizSuccess = Color(0xff00c950);

  static const colorStaticDatavizWarning = Color(0xffff8904);

  static const colorStaticEffectGlassInversePrimaryHigh = Color(0x59ffffff);

  static const colorStaticEffectGlassInversePrimaryLow = Color(0x26ffffff);

  static const colorStaticEffectGlassInversePrimaryMedium = Color(0x40ffffff);

  static const colorStaticEffectGlassPrimaryHigh = Color(0x4d262626);

  static const colorStaticEffectGlassPrimaryLow = Color(0x1a0a0a0a);

  static const colorStaticEffectGlassPrimaryMedium = Color(0x330a0a0a);

  static const colorStaticIconInversePrimary = Color(0xffffffff);

  static const colorStaticIconPrimary = Color(0xff0a0a0a);

  static const colorStaticStrokeInverseStrong = Color(0xffffffff);

  static const colorStaticStrokeInverseSubtle = Color(0x33ffffff);

  static const colorStaticSurfaceBrandCrypto = Color(0xffff5000);

  static const colorStaticSurfaceBrandPrimary = Color(0xff0165fa);

  static const colorStaticSurfaceBrandSecondary = Color(0xff00d3f3);

  static const colorStaticTextBrandSecondary = Color(0xff00d3f3);

  static const colorStaticTextInversePrimary = Color(0xffffffff);

  static const colorStaticTextPrimary = Color(0xff0a0a0a);

  static const overlayScrimHigh = Color(0xb2000000);

  static const overlayScrimInverseHigh = Color(0xccffffff);

  static const overlayScrimInverseLow = Color(0x4dffffff);

  static const overlayScrimInverseMedium = Color(0x8cffffff);

  static const overlayScrimLow = Color(0x33000000);

  static const overlayScrimMedium = Color(0x73000000);

  static const shadow2xlColor = Color(0x40000000);

  static const shadow2xsColor = Color(0x0d000000);

  static const shadowLgColor = Color(0x1a000000);

  static const shadowMdColor = Color(0x1a000000);

  static const shadowSmColor = Color(0x0d000000);

  static const shadowXlColor = Color(0x1a000000);

  static const shadowXsColor = Color(0x0d000000);

  /// Dark-mode value: #ffffff40
  static const stateOverlayHoverStrong = Color(0x330a0a0a);

  /// Dark-mode value: #ffffff1a
  static const stateOverlayHoverSubtle = Color(0x0d0a0a0a);

  /// Dark-mode value: #0a0a0a33
  static const stateOverlayInverseHoverStrong = Color(0x40ffffff);

  /// Dark-mode value: #0a0a0a0d
  static const stateOverlayInverseHoverSubtle = Color(0x1affffff);

  PepperColors._();
}
