// Generated by Claude from Figma variables via DesignBridge.
// To update: export from Figma using the DesignBridge plugin and ask Claude to sync.
//
// Naming convention (v2.0.0):
//   PepperCore* = primitives (raw values). Don't use directly.
//   Pepper*     = semantic tokens. Use these.

/// Primitive dimension scale (raw px values).
class PepperCoreDimensions {
  static const dimensionCanvasViewportWidth = 1440;

  static const dimensionCanvasViewportHeight = 1024;

  static const dimensionCanvasCanvasColumns = 12;

  static const dimensionGlobalUnit0 = 0;

  static const dimensionGlobalUnit1 = 4;

  static const dimensionGlobalUnit2 = 8;

  static const dimensionGlobalUnit3 = 12;

  static const dimensionGlobalUnit4 = 16;

  static const dimensionGlobalUnit05 = 2;

  static const dimensionGlobalUnit5 = 20;

  static const dimensionGlobalUnit6 = 24;

  static const dimensionGlobalUnit7 = 28;

  static const dimensionGlobalUnit8 = 32;

  static const dimensionGlobalUnit9 = 36;

  static const dimensionGlobalUnit10 = 40;

  static const dimensionGlobalUnit11 = 44;

  static const dimensionGlobalUnit12 = 48;

  static const dimensionGlobalUnit13 = 52;

  static const dimensionGlobalUnit14 = 56;

  static const dimensionGlobalUnit15 = 60;

  static const dimensionGlobalUnit16 = 64;

  static const dimensionGlobalUnit17 = 68;

  static const dimensionGlobalUnit18 = 72;

  static const dimensionGlobalUnit19 = 76;

  static const dimensionGlobalUnit20 = 80;

  static const dimensionGlobalUnit21 = 84;

  static const dimensionGlobalUnit22 = 88;

  static const dimensionGlobalUnit23 = 92;

  static const dimensionGlobalUnit24 = 96;

  static const dimensionGlobalUnit025 = 1;

  static const dimensionGlobalUnit25 = 100;

  static const dimensionGlobalUnit26 = 104;

  static const dimensionGlobalUnit27 = 108;

  static const dimensionGlobalUnit28 = 112;

  static const dimensionGlobalUnit29 = 116;

  static const dimensionGlobalUnit30 = 120;

  static const dimensionGlobalUnit31 = 124;

  static const dimensionGlobalUnit32 = 128;

  static const dimensionGlobalUnit33 = 132;

  static const dimensionGlobalUnit34 = 136;

  static const dimensionGlobalUnit35 = 140;

  static const dimensionGlobalUnit36 = 144;

  static const dimensionGlobalUnit37 = 148;

  static const dimensionGlobalUnit38 = 152;

  static const dimensionGlobalUnit39 = 156;

  static const dimensionGlobalUnit40 = 160;

  static const dimensionGlobalUnit41 = 164;

  static const dimensionGlobalUnit42 = 168;

  static const dimensionGlobalUnit43 = 172;

  static const dimensionGlobalUnit44 = 176;

  static const dimensionGlobalUnit45 = 180;

  static const dimensionGlobalUnit46 = 184;

  static const dimensionGlobalUnit47 = 188;

  static const dimensionGlobalUnit48 = 192;

  static const dimensionGlobalUnit49 = 196;

  static const dimensionGlobalUnit50 = 200;

  static const dimensionGlobalUnit51 = 204;

  static const dimensionGlobalUnit52 = 208;

  static const dimensionGlobalUnit53 = 212;

  static const dimensionGlobalUnit54 = 216;

  static const dimensionGlobalUnit55 = 220;

  static const dimensionGlobalUnit56 = 224;

  static const dimensionGlobalUnit57 = 228;

  static const dimensionGlobalUnit58 = 232;

  static const dimensionGlobalUnit59 = 236;

  static const dimensionGlobalUnit60 = 240;

  static const dimensionGlobalUnit61 = 244;

  static const dimensionGlobalUnit62 = 248;

  static const dimensionGlobalUnit63 = 256;

  static const dimensionGlobalUnit64 = 256;

  static const dimensionGlobalUnit65 = 260;

  static const dimensionGlobalUnit66 = 264;

  static const dimensionGlobalUnit67 = 268;

  static const dimensionGlobalUnit68 = 272;

  static const dimensionGlobalUnit69 = 276;

  static const dimensionGlobalUnit70 = 280;

  static const dimensionGlobalUnit71 = 284;

  static const dimensionGlobalUnit72 = 288;

  static const dimensionGlobalUnit73 = 292;

  static const dimensionGlobalUnit74 = 296;

  static const dimensionGlobalUnit75 = 300;

  static const dimensionGlobalUnit76 = 304;

  static const dimensionGlobalUnit77 = 308;

  static const dimensionGlobalUnit78 = 312;

  static const dimensionGlobalUnit79 = 320;

  static const dimensionGlobalUnit80 = 320;

  static const dimensionGlobalUnit81 = 324;

  static const dimensionGlobalUnit82 = 328;

  static const dimensionGlobalUnit83 = 332;

  static const dimensionGlobalUnit84 = 336;

  static const dimensionGlobalUnit85 = 340;

  static const dimensionGlobalUnit86 = 344;

  static const dimensionGlobalUnit87 = 348;

  static const dimensionGlobalUnit88 = 352;

  static const dimensionGlobalUnit89 = 356;

  static const dimensionGlobalUnit90 = 360;

  static const dimensionGlobalUnit91 = 364;

  static const dimensionGlobalUnit92 = 368;

  static const dimensionGlobalUnit93 = 372;

  static const dimensionGlobalUnit94 = 376;

  static const dimensionGlobalUnit95 = 380;

  static const dimensionGlobalUnit96 = 384;

  static const dimensionGlobalUnit97 = 388;

  static const dimensionGlobalUnit98 = 392;

  static const dimensionGlobalUnit99 = 396;

  static const dimensionGlobalUnit100 = 400;

  static const dimensionScaleSpacingNone = 0;

  static const dimensionScaleSpacing2 = 2;

  static const dimensionScaleSpacing4 = 4;

  static const dimensionScaleSpacing8 = 8;

  static const dimensionScaleSpacing12 = 12;

  static const dimensionScaleSpacing16 = 16;

  static const dimensionScaleSpacing20 = 20;

  static const dimensionScaleSpacing24 = 24;

  static const dimensionScaleSpacing28 = 28;

  static const dimensionScaleSpacing32 = 32;

  static const dimensionScaleSpacing36 = 36;

  static const dimensionScaleSpacing40 = 40;

  static const dimensionScaleSpacing48 = 48;

  static const dimensionScaleSpacing56 = 56;

  static const dimensionScaleSpacing64 = 64;

  static const dimensionScaleSpacing80 = 80;

  static const dimensionScaleSpacing96 = 96;

  static const dimensionScaleSpacing128 = 128;

  static const dimensionScaleSpacing160 = 160;

  static const dimensionScaleSpacing256 = 256;

  static const sizeScreenWidth2xl = 1440;

  static const sizeScreenWidth2xs = 320;

  static const sizeScreenWidthLg = 1024;

  static const sizeScreenWidthMd = 768;

  static const sizeScreenWidthSm = 640;

  static const sizeScreenWidthXl = 1280;

  static const sizeScreenWidthXs = 375;

  PepperCoreDimensions._();
}

/// Semantic size, spacing, and layout dimensions.
class PepperDimensions {
  static const sizeInstrumentIconSizeIcon12 = 12;

  static const sizeInstrumentIconSizeIcon16 = 16;

  static const sizeInstrumentIconSizeIcon20 = 20;

  static const sizeInstrumentIconSizeIcon24 = 24;

  static const sizeInstrumentIconSizeIcon32 = 32;

  static const sizeInstrumentIconSizeIcon40 = 40;

  static const sizeInstrumentIconSizeIcon48 = 48;

  static const sizeInstrumentIconSizeIcon64 = 64;

  static const sizeMarketingIconSizeIcon128 = 128;

  static const sizeMarketingIconSizeIcon148 = 148;

  static const sizeMarketingIconSizeIcon160 = 160;

  static const sizeMarketingIconSizeIcon192 = 192;

  static const sizeMarketingIconSizeIcon256 = 256;

  static const sizeMarketingIconSizeIcon48 = 48;

  static const sizeMarketingIconSizeIcon64 = 64;

  static const sizeMarketingIconSizeIcon80 = 80;

  static const sizeMarketingIconSizeIcon96 = 96;

  static const sizeSystemIconSizeIcon128 = 128;

  static const sizeSystemIconSizeIcon48 = 48;

  static const sizeSystemIconSizeIcon64 = 64;

  static const sizeSystemIconSizeIcon80 = 80;

  static const sizeSystemIconSizeIcon96 = 96;

  static const sizeUtilityIconSizeIcon12 = 12;

  static const sizeUtilityIconSizeIcon16 = 16;

  static const sizeUtilityIconSizeIcon20 = 20;

  static const sizeUtilityIconSizeIcon24 = 24;

  static const sizeUtilityIconSizeIcon32 = 32;

  static const sizeUtilityIconSizeIcon40 = 40;

  static const spaceInset2xs = 4;

  static const spaceInset3xs = 2;

  static const spaceInsetLg = 24;

  static const spaceInsetMd = 16;

  static const spaceInsetNone = 0;

  static const spaceInsetSm = 12;

  static const spaceInsetXl = 32;

  static const spaceInsetXs = 8;

  static const spaceGapLg = 24;

  static const spaceGapMd = 16;

  static const spaceGapNone = 0;

  static const spaceGapSm = 8;

  static const spaceGapXl = 48;

  static const spaceGapXs = 4;

  static const spaceThemeSpacingContentGapLg = 64;

  static const spaceThemeSpacingContentGapMd = 40;

  static const spaceThemeSpacingContentGapSm = 32;

  static const spaceThemeSpacingContentGapXs = 24;

  static const spaceThemeSpacingContentPadLg = 64;

  static const spaceThemeSpacingContentPadMd = 40;

  static const spaceThemeSpacingContentPadSm = 32;

  static const spaceThemeSpacingLayoutGapLg = 80;

  static const spaceThemeSpacingLayoutGapMd = 40;

  static const spaceThemeSpacingLayoutGutter = 20;

  static const spaceThemeSpacingLayoutGutterStackLg = 20;

  static const spaceThemeSpacingLayoutGutterStackMd = 20;

  static const spaceThemeSpacingLayoutGutterStackStackSm = 20;

  static const spaceThemeSpacingLayoutMargin = 80;

  static const spaceThemeSpacingLayoutPad = 80;

  static const spaceStateOverlayDisabled = 10;

  static const spaceStateOverlayInverseDisabled = 20;

  static const spaceStateOverlayInverseLoading = 10;

  static const spaceStateOverlayLoading = 5;

  static const spaceShadow2xlOffsetX = 0;

  static const spaceShadow2xlOffsetY = 24;

  static const spaceShadow2xsOffsetX = 0;

  static const spaceShadow2xsOffsetY = 1;

  static const spaceShadowLgOffsetX = 0;

  static const spaceShadowLgOffsetY = 10;

  static const spaceShadowMdOffsetX = 0;

  static const spaceShadowMdOffsetY = 4;

  static const spaceShadowSmOffsetX = 0;

  static const spaceShadowSmOffsetY = 2;

  static const spaceShadowXlOffsetX = 0;

  static const spaceShadowXlOffsetY = 20;

  static const spaceShadowXsOffsetX = 0;

  static const spaceShadowXsOffsetY = 1;

  PepperDimensions._();
}
