// Generated by Claude from Figma variables via DesignBridge.
// To update: export from Figma using the DesignBridge plugin and ask Claude to sync.
//
// Naming convention (v2.0.0):
//   PepperCore* = primitives (raw values). Don't use directly.
//   Pepper*     = semantic tokens. Use these.

import 'package:flutter/material.dart';

/// Gradients. Angles approximate the CSS `linear-gradient` direction.
class PepperGradients {
  static const iconGlassDark = LinearGradient(
    begin: Alignment.topRight,
    end: Alignment.bottomLeft,
    colors: [Color(0xff0165fa), Color(0xff00d3f3)],
  );

  static const bgBrandGradientBlue = LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
    colors: [Color(0xff0165fa), Color(0xff00d3f3)],
  );

  static const cardBgGradient = LinearGradient(
    begin: Alignment.bottomRight,
    end: Alignment.topLeft,
    colors: [Color(0xff0165fa), Color(0xff00d3f3)],
  );

  static const bgBrandGradientLight = LinearGradient(
    begin: Alignment.bottomCenter,
    end: Alignment.topCenter,
    colors: [Color(0xffe6f0ff), Color(0xffffffff)],
  );

  static const educationalBg = RadialGradient(
    colors: [Color(0xff0165fa), Color(0xff00d3f3)],
  );

  PepperGradients._();
}
