// Generated by Claude from Figma variables via DesignBridge.
// To update: export from Figma using the DesignBridge plugin and ask Claude to sync.
//
// Naming convention (v2.0.0):
//   PepperCore* = primitives (raw values). Don't use directly.
//   Pepper*     = semantic tokens. Use these.

/// Semantic border-radius tokens.
class PepperBorderRadius {
  static const 2xl = 24;

  static const 3xl = 32;

  static const full = 9999;

  static const lg = 12;

  static const md = 8;

  static const none = 0;

  static const sm = 4;

  static const xl = 16;

  static const xs = 2;

  PepperBorderRadius._();
}
