// Generated by Claude from Figma variables via DesignBridge.
// To update: export from Figma using the DesignBridge plugin and ask Claude to sync.
//
// Naming convention (v2.0.0):
//   PepperCore* = primitives (raw values). Don't use directly.
//   Pepper*     = semantic tokens. Use these.

import 'package:flutter/material.dart';

/// Elevation shadows. Use `BoxDecoration(boxShadow: [...])`.
/// Note: v2.0.0 shadows are theme-agnostic; dark-mode shadow palette lands in v2.1.
class PepperShadows {
  static const xs2 = BoxShadow(
    color: Color(0x0d000000),
    offset: Offset(0, 1),
    blurRadius: 1,
    spreadRadius: 0,
  );

  static const xs = BoxShadow(
    color: Color(0x0d000000),
    offset: Offset(0, 1),
    blurRadius: 3,
    spreadRadius: 0,
  );

  static const sm = BoxShadow(
    color: Color(0x0d000000),
    offset: Offset(0, 2),
    blurRadius: 4,
    spreadRadius: -1,
  );

  static const md = BoxShadow(
    color: Color(0x1a000000),
    offset: Offset(0, 4),
    blurRadius: 6,
    spreadRadius: -1,
  );

  static const lg = BoxShadow(
    color: Color(0x1a000000),
    offset: Offset(0, 10),
    blurRadius: 15,
    spreadRadius: -3,
  );

  static const xl = BoxShadow(
    color: Color(0x1a000000),
    offset: Offset(0, 20),
    blurRadius: 25,
    spreadRadius: -5,
  );

  static const xl2 = BoxShadow(
    color: Color(0x40000000),
    offset: Offset(0, 25),
    blurRadius: 50,
    spreadRadius: -12,
  );

  PepperShadows._();
}
