// Generated by Claude from Figma variables via DesignBridge.
// To update: export from Figma using the DesignBridge plugin and ask Claude to sync.
//
// Naming convention (v2.0.0):
//   PepperCore* = primitives (raw values). Don't use directly.
//   Pepper*     = semantic tokens. Use these.

import 'package:flutter/material.dart';

/// Role-based typography styles. Mirrors `--pepper-typography-*`.
class PepperTypography {
  static const headingH1 = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.normal,
    fontSize: 96,
    decoration: TextDecoration.none,
    letterSpacing: 0,
    height: 1.041667,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const headingH1Underlined = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.normal,
    fontSize: 96,
    decoration: TextDecoration.underline,
    letterSpacing: 0,
    height: 1.041667,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const headingH2 = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.normal,
    fontSize: 72,
    decoration: TextDecoration.none,
    letterSpacing: 0,
    height: 1.055556,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const headingH2Underlined = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.normal,
    fontSize: 72,
    decoration: TextDecoration.underline,
    letterSpacing: 0,
    height: 1.055556,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const headingH3 = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.normal,
    fontSize: 48,
    decoration: TextDecoration.none,
    letterSpacing: 0,
    height: 1.083333,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const headingH3Underlined = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.normal,
    fontSize: 48,
    decoration: TextDecoration.underline,
    letterSpacing: 0,
    height: 1.083333,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const headingH4 = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.normal,
    fontSize: 30,
    decoration: TextDecoration.none,
    letterSpacing: 0,
    height: 1.2,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const headingH4Underlined = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.normal,
    fontSize: 30,
    decoration: TextDecoration.underline,
    letterSpacing: 0,
    height: 1.2,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const headingH5 = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.normal,
    fontSize: 24,
    decoration: TextDecoration.none,
    letterSpacing: 0,
    height: 1.333333,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const headingH5Underlined = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.normal,
    fontSize: 24,
    decoration: TextDecoration.underline,
    letterSpacing: 0,
    height: 1.333333,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const headingH6 = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.normal,
    fontSize: 20,
    decoration: TextDecoration.none,
    letterSpacing: 0,
    height: 1.4,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const headingH6Underlined = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.normal,
    fontSize: 20,
    decoration: TextDecoration.underline,
    letterSpacing: 0,
    height: 1.4,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const bodyLg = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 18,
    decoration: TextDecoration.none,
    letterSpacing: 0,
    height: 1.555556,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const bodyLgUnderlined = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 18,
    decoration: TextDecoration.underline,
    letterSpacing: 0,
    height: 1.555556,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const bodyMd = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 16,
    decoration: TextDecoration.none,
    letterSpacing: 0,
    height: 1.5,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const bodyMdUnderlined = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 16,
    decoration: TextDecoration.underline,
    letterSpacing: 0,
    height: 1.5,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const bodySm = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 14,
    decoration: TextDecoration.none,
    letterSpacing: 0,
    height: 1.428571,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const bodySmUnderlined = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 14,
    decoration: TextDecoration.underline,
    letterSpacing: 0,
    height: 1.428571,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const bodyXs = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 12,
    decoration: TextDecoration.none,
    letterSpacing: 0,
    height: 1.333333,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const bodyXsUnderlined = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 12,
    decoration: TextDecoration.underline,
    letterSpacing: 0,
    height: 1.333333,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const body2xs = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 10,
    decoration: TextDecoration.none,
    letterSpacing: 0,
    height: 1.4,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const body2xsUnderlined = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 10,
    decoration: TextDecoration.underline,
    letterSpacing: 0,
    height: 1.4,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const labelLg = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w600,
    fontStyle: FontStyle.normal,
    fontSize: 18,
    decoration: TextDecoration.none,
    letterSpacing: 0,
    height: 1.555556,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const labelLgUnderlined = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w600,
    fontStyle: FontStyle.normal,
    fontSize: 18,
    decoration: TextDecoration.underline,
    letterSpacing: 0,
    height: 1.555556,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const labelMd = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w600,
    fontStyle: FontStyle.normal,
    fontSize: 16,
    decoration: TextDecoration.none,
    letterSpacing: 0,
    height: 1.5,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const labelMdUnderlined = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w600,
    fontStyle: FontStyle.normal,
    fontSize: 16,
    decoration: TextDecoration.underline,
    letterSpacing: 0,
    height: 1.5,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const labelSm = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w600,
    fontStyle: FontStyle.normal,
    fontSize: 14,
    decoration: TextDecoration.none,
    letterSpacing: 0,
    height: 1.428571,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const labelSmUnderlined = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w600,
    fontStyle: FontStyle.normal,
    fontSize: 14,
    decoration: TextDecoration.underline,
    letterSpacing: 0,
    height: 1.428571,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const labelXs = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w600,
    fontStyle: FontStyle.normal,
    fontSize: 12,
    decoration: TextDecoration.none,
    letterSpacing: 0,
    height: 1.333333,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const labelXsUnderlined = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w600,
    fontStyle: FontStyle.normal,
    fontSize: 12,
    decoration: TextDecoration.underline,
    letterSpacing: 0,
    height: 1.333333,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const label2xs = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w600,
    fontStyle: FontStyle.normal,
    fontSize: 10,
    decoration: TextDecoration.none,
    letterSpacing: 0,
    height: 1.4,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const label2xsUnderlined = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w600,
    fontStyle: FontStyle.normal,
    fontSize: 10,
    decoration: TextDecoration.underline,
    letterSpacing: 0,
    height: 1.4,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const legalMd = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 16,
    decoration: TextDecoration.none,
    letterSpacing: 0,
    height: 1.5,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const legalMdUnderlined = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 16,
    decoration: TextDecoration.underline,
    letterSpacing: 0,
    height: 1.5,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const legalXs = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 12,
    decoration: TextDecoration.none,
    letterSpacing: 0,
    height: 1.333333,
    leadingDistribution: TextLeadingDistribution.even,
  );

  static const legalXsUnderlined = TextStyle(
    fontFamily: "Manrope",
    fontWeight: FontWeight.w400,
    fontStyle: FontStyle.normal,
    fontSize: 12,
    decoration: TextDecoration.underline,
    letterSpacing: 0,
    height: 1.333333,
    leadingDistribution: TextLeadingDistribution.even,
  );

  PepperTypography._();
}
